In [61]:
import pandas as pd
from datetime import date

In [2]:
df = pd.read_csv('csv/video_data_04-11-22.csv')

In [22]:
df.head()

,Id,Title,Published_date,Views,Likes,Comments,Duration
0,V0jlhEAScls,NBA I En İyi Oyunlar,2022-11-04T07:00:11Z,341,14,0,PT1M18S
1,EE9j8Vjslcs,Denver Nuggets - Oklahoma City Thunder Maç Öze...,2022-11-04T06:38:33Z,124,4,0,PT1M36S
2,2Mo1uJpiBl4,Golden State Warriors - Orlando Magic Maç Özet...,2022-11-04T06:38:30Z,393,7,2,PT2M3S
3,vN2q_eycKWw,Olimpia Milano - Real Madrid (77-83) - Maç Öze...,2022-11-03T22:12:26Z,4713,70,8,PT9M9S
4,y2mZrITfk7c,Bayern Münih - Anadolu Efes (81-78) - Maç Özet...,2022-11-03T21:48:40Z,22085,299,99,PT8M19S

In [15]:
def copy_df(df):
    return df.copy()

In [42]:
def feature_extraction(df):
    def categorize(title):

        Basketball = ['NBA','Boston Celtics','Brooklyn Nets','Philadelphia 76ers','Toronto Raptors','Chicago Bulls','New York Knicks',
                  'Cleveland Cavaliers','Detroit Pistons','Indiana Pacers','Milwaukee Bucks','Atlanta Hawks','Charlotte Hornets',
                  'Miami Heat','Orlando Magic','Washington Wizards','Denver Nuggets','Minnesota Timberwolves','Oklahoma City Thunder',
                  'Portland Trail Blazers','Utah Jazz','Golden State Warriors','LA Clippers','Los Angeles Lakers','Phoenix Suns',
                  'Sacramento Kings','Dallas Mavericks','Houston Rockets','Memphis Grizzlies','New Orleans Pelicans','San Antonio Spurs',
                  'All Star',

                  'EuroCup','FIBA','EuroLeague',

                 'Cedi Osman','Kobe Bryant','Smaç','Blok','Curry','LeBron James','Durant','Harden',
                'Doncic','Virtus Bologna','Virtus Pallacanestro Bologna','Kyrie Irving','Fenerbahçe Beko','euroleague']

        Soccer = ['LaLiga','Athletic Club','Athletico','Osasuna','Cadiz','Elche','Barcelona','Getafe','Girona','Vallecona',
              'Celta','Espanyol','Mallorca',
             'Betis','Real Madrid','Sociedad','Valladolid','Sevilla','Almeria','Valencia','Villarreal',
             'SERIE A','#SerieA','SerieA','Atalanta','Bologna','Cremonese','Empoli','Fiorentina','Verona','Inter',

              'Juventus','Lazio','Lecce','Milan','Monza',
           'Napoli','Roma','Salernitana','Sampdoria','Sassuolo','Spezia','Torino','Udinese',

             'EURO 2020','UEFA Nations League','#NationsLeague','2022 Dünya Kupası Avrupa Elemeleri',
             'Copa America 2021','Finalissima','Fenerbahçe',
              'Türkiye','Fransa','Arjantin','İspanya','İtalya','Portekiz','Almanya','Belçika','Galler','Hollanda','İngiltere',
              'Hazırlık Maçı',

             'Gol','Frikik','Karim Benzema','Robert Lewandowski','FRİKİK',
            'Vedat Muruqi','Burak Yilmaz','Skor','Haaland','Messi','Ronaldo','Hakan Çalhanoğlu','Jürgen Klopp','Ibrahimovic',
             'Zlatan Ibrahimović','Burak Yilmaz','Gareth Bale','De Gea','GOLÜ','Gol',
             'İlkay Gündoğan','Pep Guardiola','Jose Mourinho','Kevin De Bruyne','Paulo Dybala','Angel Di Maria',
             'Riyad Mahrez','Vinicius Junior']

        Tennis = ['Wimbledon','ATP','Djokovic','Federer','Nadal','Barcelona Open']

        Fighting = ['UFC','WWE',
                'Khabib','Conor McGregor','Gökhan Saki',
              'Rey Mysterio','Alexa','The Fiend','Randy','Undertaker','Cena','Roman Reigns','Goldberg','Anthony Joshua','Boks']

        Racing = ['MotoGP','Formula 2','Formula 1','Son Viraj','Cem Bölükbaşı','Hamilton','Verstappen','Perez','Valencia Grand Prix']

        for cat in Basketball:
            if cat.lower() in str(title).lower():
                return 'Basketball'

        for cat in Tennis:
            if cat.lower() in str(title).lower():
                return 'Tennis'

        for cat in Fighting:
            if cat.lower() in str(title).lower():
                return 'Fighting'

        for cat in Racing:
            if cat.lower() in str(title).lower():
                return 'Racing'

        if 'Altın Oran' in str(title):
            return 'Betting'

        for cat in Soccer:
            if cat.lower() in str(title).lower():
                return 'Soccer'

        if 'GP' in str(title):
            return 'Racing'
    
    
    df['Categories'] = df['Title'].apply(categorize)
    
        
    
    def subcategorize(title):
            
        LaLiga = ['LaLiga','Athletic Club','Athletico','Osasuna','Cadiz','Elche','Barcelona',
              'Getafe','Girona','Vallecona','Celta','Espanyol','Mallorca',
             'Betis','Real Madrid','Sociedad','Valladolid','Sevilla','Almeria','Valencia','Villarreal']

        SerieA=['SERIE A','#SerieA','SerieA','Atalanta','Bologna','Cremonese','Empoli','Fiorentina',
            'Verona','Inter','Juventus','Lazio','Lecce','Milan','Monza',
           'Napoli','Roma','Salernitana','Sampdoria','Sassuolo','Spezia','Torino','Udinese']

        International = ['EURO 2020','UEFA Nations League','#NationsLeague','2022 Dünya Kupası Avrupa Elemeleri',
                     'Copa America 2021','Finalissima','Fenerbahçe',
                    'Türkiye','Fransa','Arjantin','İspanya','İtalya','Portekiz','Almanya','Belçika','Galler','Hollanda','İngiltere',
                    'Hazırlık Maçı']

        Soccer_Highlights = ['Gol','Frikik','Karim Benzema','Robert Lewandowski','Burak Yilmaz','FRİKİK',
                         'Vedat Muruqi','Burak Yilmaz','Skor','Haaland','Messi','Ronaldo','Hakan Çalhanoğlu',
                        'Jürgen Klopp','Ibrahimovic','Zlatan Ibrahimović','Gareth Bale','De Gea','GOLÜ','Gol',
                        'İlkay Gündoğan','Pep Guardiola','Jose Mourinho','Kevin De Bruyne','Paulo Dybala','Angel Di Maria',
                        'Riyad Mahrez','Vinicius Junior']

        NBA = ['NBA','Boston Celtics','Brooklyn Nets','Philadelphia 76ers','Toronto Raptors','Chicago Bulls','New York Knicks',
                  'Cleveland Cavaliers','Detroit Pistons','Indiana Pacers','Milwaukee Bucks','Atlanta Hawks','Charlotte Hornets',
                  'Miami Heat','Orlando Magic','Washington Wizards','Denver Nuggets','Minnesota Timberwolves','Oklahoma City Thunder',
                  'Portland Trail Blazers','Utah Jazz','Golden State Warriors','LA Clippers','Los Angeles Lakers','Phoenix Suns',
                  'Sacramento Kings','Dallas Mavericks','Houston Rockets','Memphis Grizzlies','New Orleans Pelicans','San Antonio Spurs',
          'All Star']

        European_Basketball = ['EuroCup','FIBA','EuroLeague']

        Basketball_Highlights = ['Cedi Osman','Kobe Bryant','Smaç','Blok','Curry','LeBron James','Durant','Harden',
                             'Doncic','Virtus Bologna','Virtus Pallacanestro Bologna','Kyrie Irving','Fenerbahçe Beko']


        Racing_Highlights = ['Cem Bölükbaşı','Hamilton','Verstappen','Perez','Valencia Grand Prix']

        Tennis_Highlights = ['Djokovic','Federer','Nadal','Barcelona Open']

        Fighting_Highlights = ['Khabib','Conor McGregor','Gökhan Saki',
                          'Rey Mysterio','Alexa','The Fiend','Randy','Undertaker','Cena','Roman Reigns','Goldberg',
                           'Anthony Joshua','Boks']

        #Other
        if 'Altın Oran'.lower() in str(title).lower():
            return 'Betting'

        #Tennis
        if 'Wimbledon'.lower() in str(title).lower():
            return 'Wimbledon'

        if 'ATP'.lower() in str(title).lower():
            return 'ATP'



        #Racing
        if 'MotoGP'.lower() in str(title).lower():
            return 'MotoGP'

        if 'Formula 2'.lower() in str(title).lower():
            return 'Formula 2'

        if 'Formula 1'.lower() in str(title).lower():
            return 'Formula 1'

        if 'Son Viraj'.lower() in str(title).lower():
            return 'Son Viraj'

        for cat in Racing_Highlights:
            if cat.lower() in str(title).lower():
                return 'Racing_Highlights'

        if 'GP' in str(title):
            return 'Racing_Highlights'

        #Fighting
        if 'UFC'.lower() in str(title).lower():
            return 'UFC'

        if 'WWE'.lower() in str(title).lower():
            return 'WWE'

        for cat in Fighting_Highlights:
            if cat.lower() in str(title).lower():
                return 'Fighting_Highlights'

        #Basketball
        for cat in NBA:
            if cat.lower() in str(title).lower():
                return 'NBA'

        for cat in European_Basketball:
            if cat.lower() in str(title).lower():
                return 'European_Basketball'

        for cat in Basketball_Highlights:
            if cat.lower() in str(title).lower():
                return 'Basketball_Highlights'

        for cat in Tennis_Highlights:
            if cat.lower() in str(title).lower():
                return 'Tennis_Highlights'

        #Soccer
        for cat in LaLiga:
            if cat.lower() in str(title).lower():
                return 'LaLiga'

        for cat in SerieA:
            if cat.lower() in str(title).lower():
                return 'SerieA'

        for cat in International:
            if cat.lower() in str(title).lower():
                return 'International'

        for cat in Soccer_Highlights:
            if cat.lower() in str(title).lower():
                return 'Soccer_Highlights'
    
    df['SubCategory'] = df['Title'].apply(subcategorize)
    
    
    return df

In [34]:
def drop_na(df):
    return df.dropna()

In [53]:
def duration_convert(df):
    def convert_YouTube_duration_to_seconds(duration):
        day_time = duration.split('T')
        day_duration = day_time[0].replace('P', '')
        day_list = day_duration.split('D')
        if len(day_list) == 2:
            day = int(day_list[0]) * 60 * 60 * 24
            day_list = day_list[1]
        else:
            day = 0
            day_list = day_list[0]
        hour_list = day_time[1].split('H')
        if len(hour_list) == 2:
            hour = int(hour_list[0]) * 60 * 60
            hour_list = hour_list[1]
        else:
            hour = 0
            hour_list = hour_list[0]
        minute_list = hour_list.split('M')
        if len(minute_list) == 2:
            minute = int(minute_list[0]) * 60
            minute_list = minute_list[1]
        else:
            minute = 0
            minute_list = minute_list[0]
        second_list = minute_list.split('S')
        if len(second_list) == 2:
            second = int(second_list[0])
        else:
            second = 0
        return day + hour + minute + second
    
    df['DurationinSeconds'] = df['Duration'].apply(convert_YouTube_duration_to_seconds)
    return df

In [50]:
def date_convert(df):
    df['Date'] = df['Published_date'].apply(lambda x:x.split('T')[0])
    return df

In [51]:
def year_convert(df):
    df['Year'] = df['Date'].apply(lambda x:x.split('-')[0])
    return df

In [62]:
def video_age(df):
    def daysdiff(time):
        year = time.split('-')[0]
        month = time.split('-')[1]
        day = time.split('-')[2]

        d = date.today() - date(int(year),int(month),int(day))

        return d.days
    df['Age'] = df['Date'].apply(daysdiff)
    return df

In [68]:
def type_convert(df):
    df['Date'] = pd.to_datetime(df['Date'])
    df['Categories'] = df['Categories'].astype('category')
    df['SubCategory'] = df['SubCategory'].astype('category')
    df['Year'] = df['Year'].astype('category')
    
    return df

In [69]:
def fe_data(df):
    df_cleaned = (df.
                  pipe(copy_df).
                  pipe(feature_extraction).
                  pipe(drop_na).
                  pipe(duration_convert).
                  pipe(date_convert).
                  pipe(year_convert).
                  pipe(video_age).
                  pipe(type_convert)
                 )
    return df_cleaned

In [71]:
new_df = fe_data(df)

In [72]:
new_df

,Id,Title,Published_date,Views,Likes,Comments,Duration,Categories,SubCategory,DurationinSeconds,Date,Year,Age
0,V0jlhEAScls,NBA I En İyi Oyunlar,2022-11-04T07:00:11Z,341,14,0,PT1M18S,Basketball,NBA,78,2022-11-04,2022,1
1,EE9j8Vjslcs,Denver Nuggets - Oklahoma City Thunder Maç Öze...,2022-11-04T06:38:33Z,124,4,0,PT1M36S,Basketball,NBA,96,2022-11-04,2022,1
2,2Mo1uJpiBl4,Golden State Warriors - Orlando Magic Maç Özet...,2022-11-04T06:38:30Z,393,7,2,PT2M3S,Basketball,NBA,123,2022-11-04,2022,1
3,vN2q_eycKWw,Olimpia Milano - Real Madrid (77-83) - Maç Öze...,2022-11-03T22:12:26Z,4713,70,8,PT9M9S,Basketball,European_Basketball,549,2022-11-03,2022,2
4,y2mZrITfk7c,Bayern Münih - Anadolu Efes (81-78) - Maç Özet...,2022-11-03T21:48:40Z,22085,299,99,PT8M19S,Basketball,European_Basketball,499,2022-11-03,2022,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9401,rhqyn6P2amI,Anthony Joshua vs. Joseph Parker - Full Fight ...,2018-04-01T07:48:53Z,238886,1357,125,PT4H9M41S,Fighting,Fighting_Highlights,14981,2018-04-01,2018,1679
9402,LDFJC9UxPPI,Gökhan Saki Henrique Da Silva'yı Nakavt ile De...,2018-03-22T15:05:39Z,9893,73,7,PT24S,Fighting,Fighting_Highlights,24,2018-03-22,2018,1689
9403,kJ1UsnQ2ew4,Son Sektörde Nefesler Tutuldu! (MotoGP 2018 - ...,2018-03-22T12:48:52Z,4681,46,7,PT1M36S,Racing,MotoGP,96,2018-03-22,2018,1689
9407,btVGCtXxKzg,Marc Marquez'in Şampiyonluk Heyecanı! (MotoGP ...,2018-03-09T12:17:55Z,353,4,4,PT2M7S,Racing,MotoGP,127,2018-03-09,2018,1702
9408,xQgGHq76X7Q,Marquez Hata Yaptı Ama... (MotoGP 2017 - Valen...,2018-03-09T12:17:55Z,1105,13,3,PT34S,Racing,MotoGP,34,2018-03-09,2018,1702

In [73]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8561 entries, 0 to 9408
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 8561 non-null   object
 1   Title              8561 non-null   object
 2   Published_date     8561 non-null   object
 3   Views              8561 non-null   int64
 4   Likes              8561 non-null   int64
 5   Comments           8561 non-null   int64
 6   Duration           8561 non-null   object
 7   Categories         8561 non-null   category
 8   SubCategory        8561 non-null   category
 9   DurationinSeconds  8561 non-null   int64
 10  Date               8561 non-null   datetime64[ns]
 11  Year               8561 non-null   category
 12  Age                8561 non-null   int64
dtypes: category(3), datetime64[ns](1), int64(5), object(4)
memory usage: 761.9+ KB

In [75]:
new_df['Date']

0      2022-11-04
1      2022-11-04
2      2022-11-04
3      2022-11-03
4      2022-11-03
          ...
9401   2018-04-01
9402   2018-03-22
9403   2018-03-22
9407   2018-03-09
9408   2018-03-09
Name: Date, Length: 8561, dtype: datetime64[ns]

In [76]:
new_df.columns

Index(['Id', 'Title', 'Published_date', 'Views', 'Likes', 'Comments',
       'Duration', 'Categories', 'SubCategory', 'DurationinSeconds', 'Date',
       'Year', 'Age'],
      dtype='object')

In [78]:
arr = ['Id','Title','Date','Comments','Likes','Views','Duration','Categories','SubCategory']